### ISSUE TITLE
Code size is too large

### ISSUE THREAD

**Issue by sengtha** [lich666dead/zil-pay#13]
I have written smart contract. There are about 620 line of source code. Whent I tried to deploy, There is nothing happened and I saw Code size is too large error message on browser console.

**Comment by lich666dead** [comment]
hello dear sengtha, thank you for help in develop, you didn't try deploy through native jsonRPC?

**Comment by lich666dead** [comment]
this code [Zilliqa protocol](https://github.com/Zilliqa/Zilliqa/blob/3121684960a9b20bc341cb83de3fdf5c93391299/src/libServer/LookupServer.cpp#L320). Wallet ZilPay proxyed all requests to node including errors. This issues will be open until we decide it problem!

**Comment by lich666dead** [comment]
To make it work, you need split contract on some parts.
