### ISSUE TITLE
Can send just one tx at once...

### ISSUE THREAD

**Issue by reb0rn21** [lich666dead/zil-pay#6]
From one account I can send only one TX at once, then I need to wait to be accepted by blockchain to send next or 2nd one is stuck

sending from 10 accounts at same time (one tx per account) works, but not from one

**Comment by lich666dead** [comment]
hello, thank you for participating in the development, the problem is that each follow-up transaction is created with the same nonce. The problem will be solved in the next update 0.0.8

**Comment by lich666dead** [comment]
bug fix on commit: https://github.com/lich666dead/zil-pay/commit/5e45054939c80b958b8a82d603af10942e70c601

**Comment by reb0rn21** [comment]
Lat version 0.16 same issue is back... pls check
